apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: mkcluster
  region: ap-south-1

nodeGroups:
  - name: ng1
    instanceType: t2.micro
    desiredCapacity: 1
  - name: ng2
    instanceType: t2.small
    desiredCapacity: 1